// User reducer types
export const UserTypes = {
	SET_AUTHENTICATED: 'SET_AUTHENTICATED',
	SET_UNAUTHENTICATED: 'SET_UNAUTHENTICATED',
	SET_USER: 'SET_USER',
	LOADING_USER: 'LOADING_USER'
};

// UI reducer types
export const UITypes = {
	SET_ERRORS: 'SET_ERRORS',
	CLEAR_ERRORS: 'CLEAR_ERRORS',
	LOADING_START: 'LOADING_FINISH',
	LOADING_FINISH: 'LOADING_START',
	SET_OPEN: 'SET_OPEN',
	SET_CLOSE: 'SET_CLOSE'
};
